import type { NextPage } from "next";
import Head from "next/head";
import { WithEffect } from "../components/WithEffect";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Geetest Captcha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>Geetest Captcha</h2>

        <WithEffect />

        <a
          href="http://"
          target="_blank"
          rel="noopener noreferrer"
          className="githubLink"
        >
          GitHub
        </a>
      </main>
    </>
  );
};

export default Home;
